version: '3.8'

services:
  library-api:
    image: yorokobiii/libraryonline:latest
    container_name: libraryonline-container
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    restart: unless-stopped
    volumes:
      - library-data:/app/Data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  library-data:
    driver: local